"""Initial Migration

Revision ID: 415f081e566b
Revises: 33a0ded112cb
Create Date: 2018-09-05 10:04:32.377478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415f081e566b'
down_revision = '33a0ded112cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
